In [1]:
import numpy as np 


x = np.arange(24).reshape(2,3,4)


x.strides


(96, 32, 8)

In [19]:
# slicing 


x = list(range(20))

x[5:10]

x[3:16:3]

[3, 6, 9, 12, 15]

In [ ]:
x = np.arange(30).reshape(5,6)

x
np.vstack(x[:,3])


x[2:4, 3:5] # returns a two dimensional array as a slice 

array([[15, 16],
       [21, 22]])

In [ ]:
a = np.arange(0,200,2).reshape(2,25,2)
a
# looping through columns 

for j in range(a.shape[1]): # grabbing the column values

    col = a[:,j]
    print(col)

[[  0   2]
 [100 102]]
[[  4   6]
 [104 106]]
[[  8  10]
 [108 110]]
[[ 12  14]
 [112 114]]
[[ 16  18]
 [116 118]]
[[ 20  22]
 [120 122]]
[[ 24  26]
 [124 126]]
[[ 28  30]
 [128 130]]
[[ 32  34]
 [132 134]]
[[ 36  38]
 [136 138]]
[[ 40  42]
 [140 142]]
[[ 44  46]
 [144 146]]
[[ 48  50]
 [148 150]]
[[ 52  54]
 [152 154]]
[[ 56  58]
 [156 158]]
[[ 60  62]
 [160 162]]
[[ 64  66]
 [164 166]]
[[ 68  70]
 [168 170]]
[[ 72  74]
 [172 174]]
[[ 76  78]
 [176 178]]
[[ 80  82]
 [180 182]]
[[ 84  86]
 [184 186]]
[[ 88  90]
 [188 190]]
[[ 92  94]
 [192 194]]
[[ 96  98]
 [196 198]]


In [54]:
x = np.random.randint(1,100, size = 24) #generates list of random numbers with defined size. 

print(f'x= {x}')

x = x.reshape(4,6)

print(f'x =  \n {x}')

#axis 0 means column wise
print('col x min=', (np.vstack
                     (x.min(axis=0)))) #this takes the min value of the first column in x 

#axis 1 means row wise


x= [30 73 19 39 54  1 84 86 65 18 96 26 72 90 14  7 40 92 88 58 64 36 82 26]
x =  
 [[30 73 19 39 54  1]
 [84 86 65 18 96 26]
 [72 90 14  7 40 92]
 [88 58 64 36 82 26]]
col x min= [[30]
 [58]
 [14]
 [ 7]
 [40]
 [ 1]]


Some other methods: flatten and ravel 

In [76]:
x = np.arange(24).reshape(4,6)

x [0,0] = 99


y = np.ravel(x)

y[0]= 100 

print(f'y = \n {y}')
print(f'x= \n {x}')


z = (x).flatten() # flatten is creating a whole new array n one dimension 
z[-1] = 42

print(f'y = \n {y}')
print(f'x= \n {x}')
print(z)


y = 
 [100   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23]
x= 
 [[100   1   2   3   4   5]
 [  6   7   8   9  10  11]
 [ 12  13  14  15  16  17]
 [ 18  19  20  21  22  23]]
y = 
 [100   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23]
x= 
 [[100   1   2   3   4   5]
 [  6   7   8   9  10  11]
 [ 12  13  14  15  16  17]
 [ 18  19  20  21  22  23]]
[100   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  42]


In [ ]:
import pandas as pd

import numpy as np

def read_csv_to_dict(filename): 
    dta = pd.read_csv(filename)

    dta_dict = dta.to_dict(orient= 'list')
    return dta_dict

df = read_csv_to_dict('SBUX.csv')

low = np.array(df['low'], dtype=float) # this is how you modify the 

high = np.array(df['high'], dtype = int)

vals = np.array([df['high'], df['low']], dtype= float)



array([ 91.41000366,  91.80000305,  91.94000244,  91.86000061,
        92.01000214,  91.93000031,  91.37999725,  92.51999664,
        92.94999695,  92.87000275,  95.09999847,  95.41000366,
        97.45999908,  97.01999664,  97.62000275,  98.09999847,
        98.58999634, 102.68000031, 108.02999878, 107.5       ,
       105.51999664, 108.12999725, 109.86000061, 111.05000305,
       110.05999756, 111.        , 110.61000061, 110.40000153,
       111.52999878, 112.02999878, 111.62000275, 112.33999634,
       111.95999908, 111.62999725, 111.88999939, 112.66999817,
       112.26000214, 112.80000305, 114.26999664, 114.09999847,
       112.        , 110.20999908, 104.91000366, 103.44000244,
        99.80000305,  99.        ,  96.97000122,  95.93000031,
        96.16000366,  97.        ,  97.68000031,  97.94999695,
        98.66999817,  96.29000092,  95.62999725,  94.76999664,
        96.        ,  97.54000092,  97.05999756,  94.58000183,
        97.12999725,  97.41000366,  87.65000153,  81.30