# Homework 8


**Concepts covered:**

numpy, array operations, linear algebra


**Instructions:**

Be sure to run each code block after you edit it to make sure it runs as expected. When you are done, we strongly recommend you run all the code from scratch (Runtime menu -> Restart and Run all) to make sure your current code works for all problems.

If your code raises an exception when run from scratch, it will interfere with the auto-grader process causing you to lose some or all points for this homework. Please ask for help on Piazza, attend office hours or schedule an appointment with your learning facilitator if you get stuck.

**Warning about AI:**

While we encourage you to use AI to generate practice problems, **we recommend against using generative AI in the strongest terms** to solve any part of this assignment. The goal of this assignment is for you to learn these concepts, and while using AI may help you obtain solutions to these problems, you will cheat yourself out of the learning that comes from working through the problems yourself.

**Sample Output:**

For each problem description, a sample output has been included to show what the expected output should be.
Some functions have test cases provided for you to test with, so no sample output has been included for those.


**Docstrings and Comments:**

Include a *documentation string* (docstring) for each function definition, as well as comments in the body of your code to explain each control structures (e.g., decision, loop), function call, or formula.

The following starter code will be used in several problems. Run the following cell before continuing.

In [2]:
# imports
import numpy as np

**Review Problem 1**

**Concept:** *Numpy arrays.*

**Task:**

Write a function `max_column_sum(a)` that takes a 2D numpy array and:

1. Computes the sum of each column

2. Returns the largest column sum (a number)

**Sample Output:**

Consider this array `a`:
```
a = np.array([[ 7, -2,  5, 1],
              [ 3,  4, -6, 9],
              [-1,  8,  2, 0]])
```
If we call the function `max_column_sum(a)`, it should return `10`.


In [ ]:
# TO DO: WRITE YOUR SOLUTION HERE

def max_column_sum(a): 

    '''Here we are taking the sum columns wise and then taking the max value'''

    column_sums = np.sum(a,axis= 0)
    return np.max(column_sums)


Test cases for problem 1

In [18]:
# WRITE YOUR TEST CASES HERE
a = np.array([[ 7, -2,  5, 1],
              [ 3,  4, -6, 9],
              [-1,  8,  2, 0]])

max_column_sum(a) 


np.int64(10)

**Review Problem 2**

**Concept:** *Numpy arrays, if statement, loops.*

**Task:**

Write a function `check_row_sum(x, value)` that takes a 2D numpy array `x` and a number `value`, and returns:

* `True` if every row sum is within 0.001 of `value`

* `False` otherwise

**Sample Output:**

Consider this array `x`:

```
x = np.array([[2.0, 1.0, 3.0],
              [4.5, 0.5, 1.0],
              [1.2, 2.3, 2.5]])
```
If we call the function `check_row_sum(x, value)`, it should return `True`.


In [ ]:
# TO DO: WRITE YOUR SOLUTION HERE

def check_row_sum(x , value): 

    '''This looks at the rows of x, subracts their sum from a value, and then takes their absoulte value to determine if they are 0.001 away from the cutoff'''
    
    for row in x: 
        if abs(np.sum(row) -value) > 0.001: # this is checking if the difference in the sum of rows in x is >0.01 of the target value
            return False
        
    return True

Test cases for problem 2

In [155]:
# WRITE YOUR TEST CASES HERE

x = np.array([[2.0, 1.0, 3.0],
              [4.5, 0.5, 1.0],
              [1.2, 2.3, 2.5]])

check_row_sum(x, 6)

True

**Problem 3**

**Concept:** *Numpy arrays.*

**Task:**

Write `check_value(a, b, value)` where:

* `a` is n×1

* `b` is 1D length m (or 1×m)

* Return `True` if any `a[i] + b[j] == value`, else `False`.

**Sample Output:**

Consider this array `a`:

```
a = np.array([[15],
              [60],
              [90]])
b = np.array([5, 25, 40])
```

If we call the function `check_value(a, b, value)`, it should return `True`.



In [ ]:
# TO DO: WRITE YOUR SOLUTION HERE


def check_value(a, b, value):

    '''Funciton takes the rows of a and then the values in the array b and tests if the sum of which equals the defined value'''

    for i in range(a.shape[0]):

        for j in range(len(b)):

            if a[i, 0] + b[j] == value: # i,0 means row i column 0 (or the first column in other words)
                return True
    return False

Test cases for problem 3

In [85]:
# WRITE YOUR TEST CASES HERE
a = np.array([[15],
              [60],
              [90]])
b = np.array([5, 25, 40])

check_value(a,b,100)

False

**Problem 4**

**Concept:** *Numpy arrays.*

**Task:**

Write `dot_prod(a, b)` to compute the matrix product `a @ b` if dimensions are compatible.

If not compatible, print an error in this format: 'Incompatible dimensions: {shape of a} with {shape of b}.' and return `None`.

**Sample Output:**

Consider the following arrays `a` and `b`:

```
a = np.array([[1, 3, 2],
              [0, 5, 4]])
b = np.array([[2, 1],
              [0, 3],
              [1, 2]])
```

If we call the function `dot_prod(a, b)`, it should return:
```
[[ 4 14], [ 4 23]]

In [ ]:
# TO DO: WRITE YOUR SOLUTION HERE

# arrays can be multiplied if the number of columns of the first are the same as the number of rows in the second. 


def dot_prod(a,b): 

    '''This checks that the number of columns in a are equal to the number of rows in b and then returns a multiplied matrix of a and b'''

    a_rows = a.shape[1] # number of columns in a 

    b_cols = b.shape[0] # number of rows in b 

    if a_rows == b_cols: 
        return a @ b
    
    else: 
        return print(f'Incompatible dimensions: {a.shape} with {b.shape}')



Test cases for problem 4

In [79]:
# WRITE YOUR TEST CASES HERE

a = np.array([[1, 3, 2],
              [0, 5, 4]])
b = np.array([[2, 1],
              [0, 3],
              [1, 2]])


dot_prod(a, b)

array([[ 4, 14],
       [ 4, 23]])

**Problem 5**

**Concept:** *Numpy arrays, views, flatten.*


**Task:**

Write `view_proportion(x)` that:

* Returns `None` if `x` is not a view

* Otherwise returns `(# of elements visible in x) / (# of elements in original base array)`

**Sample Output:**

Consider the following:
```
base = np.arange(40)
x = base[10:30:2]  
```
If we call the function `view_proportion(x)`, it should return `0.25`.

There are 10 elements in the view and 40 in the base → 10/40 = 0.25


In [ ]:
# TO DO: WRITE YOUR SOLUTION HERE

#x.size returns the number of elements in x 

# x.base is the original array with 40 elements 


def view_proportion(x): 

    '''This uses x.base to check if the x is a view of an original array, and then divides the size of origninal x by the view size.'''

    if x.base is None: # this tells you whether x came from another array
        return None
    
    else: 
        return x.size / x.base.size # 10 / 40 in our test case 
    



Test cases for problem 5

In [51]:
# WRITE YOUR TEST CASES HERE

base = np.arange(40)
x = base[10:30:2]  


view_proportion(x)

0.25

**Problem 6**

**Concept:** *Numpy arrays, shape, flatten, slicing.*


**Task:**

Write `diagonal(x)` that returns the diagonal elements of a 2D array:
`x[0,0], x[1,1], x[2,2], ...` up to the largest valid diagonal.


**Sample Output:**

Consider this array `x`:
```
v
```
If we call the function `diagonal(x)` , it should return:
```
[ 4, -2, 10, 7]
``` 



In [166]:
# TO DO: WRITE YOUR SOLUTION HERE


def diagonal(x): 

    '''This is taking the rows and columns of the x shape and then '''

    n = min(x.shape[0], x.shape[1]) # defining n as the rows and columns in the matrix of x 

    return x[np.arange(n), np.arange(n)]




Test cases for problem 6

In [167]:
# WRITE YOUR TEST CASES HERE

x = np.array([[ 4,  8,  1,  9],
              [ 7, -2,  6,  0],
              [ 5,  3, 10, 11],
              [12,  2, -1,  7]])


diagnoal(x)

array([ 4, -2, 10,  7])

**Problem 7**

**Concept:** *Numpy arrays, broadcasting.*

**Task:**

The [$X + Y$ sorting problem](https://en.wikipedia.org/wiki/X_%2B_Y_sorting) considers pairs of numbers from two lists, $X$ and $Y$, and examines their sums.

Write a function `x_y_sorting(x, y)` that takes two 1D numpy arrays, `x` and `y`, as input.

The function should return a numpy array `z` where each element is the sum of an element from `x` and an element from `y`.

Specifically, the element in row `i` and column `j` of the output array should be:

$$
z[i,j]=x[i]+y[j]
$$

You should use numpy broadcasting to compute this efficiently rather than using nested loops.

The resulting array elements should be sorted in ascending order.

**Sample Output:**

Consider the following arrays `x` and `y`:
```
x = np.array([3, 7, -1, 0])
y = np.array([10, 2])
```
If we call the function `x_y_sorting(x, y)`, it should return:

```
[1, 2, 5, 9, 9, 10, 13, 17]
```


In [164]:
# TO DO: WRITE YOUR SOLUTION HERE


def x_y_sorting(x,y): 


    '''Here we are taking the rows of x and the columns of y and adding them together'''

    z = x[:,None] + y[None,:] # this is looking at all rows of x and all columns of y 

    return np.sort(z.ravel()) # the ravel() function turns any array into one dimension 
            
    


Test cases for problem 7

In [165]:
# WRITE YOUR TEST CASES HERE


x = np.array([3, 7, -1, 0])
y = np.array([10, 2])



x_y_sorting(x,y)

array([ 1,  2,  5,  9,  9, 10, 13, 17])

**Problem 8**

**Concept:** *Numpy arrays, hstack.*

**Task:**

Write a function `row_stats(x)` that takes an n×k numpy array as input.

The function should compute three statistics for each row of the array:

1. The minimum value of the row

2. The median value of the row

3. The maximum value of the row

The function should return a new n×3 numpy array where:

* Column 0 contains the minimum values

* Column 1 contains the median values

* Column 2 contains the maximum values

Use numpy functions such as `min`, `median`, and `max` with the appropriate axis, and combine the results using `np.hstack()`.


**Sample Output:**

Consider this array `x`:

```
x = np.array([[ 6,  2,  9,  4],
              [11,  3,  3,  8],
              [-5,  0,  5, 10]])
```

If we call the function `row_stats(x)`, it should return:
```
[[ 2. , 5. , 9. ], [ 3. , 5.5, 11. ], [-5. , 2.5, 10. ]]
```


In [ ]:
# TO DO: WRITE YOUR SOLUTION HERE



def row_stats(x): 

    '''Here we are computing the stats of the array rowwise and then rehaping them to a one column to then stack using hstack'''

    mins = np.min(x, axis = 1).reshape(-1,1)

    meds = np.median(x, axis = 1).reshape(-1,1)

    maxes = np.max(x, axis = 1).reshape(-1,1)

    return np.hstack((mins,meds, maxes)) # this makes a matrix of values with the desired elements that we defined above. 


Test cases for problem 8

In [120]:
# WRITE YOUR TEST CASES HERE

x = np.array([[ 6,  2,  9,  4],
              [11,  3,  3,  8],
              [-5,  0,  5, 10]])

row_stats(x)

array([[ 2. ,  5. ,  9. ],
       [ 3. ,  5.5, 11. ],
       [-5. ,  2.5, 10. ]])

**Problem 9**

**Concept:** *Numpy arrays, accumulator pattern.*

**Task:**

Write a function `harmonic_numbers(n)` that takes a positive integer `n` and returns a 1D numpy array of length `n` containing the first `n` harmonic numbers.

The harmonic numbers are defined as:

$$H_n = 1 + \frac{1}{2} + \frac{1}{3} + ... + \frac{1}{n}$$


Your array should contain:

* The first element equal to 1

* Each subsequent element computed using the previous value

Specifically:

$$
result[i] = result[i-1] + \frac{1}{i+1}
$$



Make sure to test your function with a large value such as `n = 100000` to confirm that your implementation runs efficiently.



**Sample Output:**

If we call the function `harmonic_numbers(n)` where `n = 6`, it should return:
```
[1. , 1.5 , 1.83333333, 2.08333333, 2.28333333, 2.45]
```


In [ ]:
# TO DO: WRITE YOUR SOLUTION HERE



def harmonic_numbers(n):

    '''Here we are taking the cum sum of n beginning with one as defined in the np.arrange function to the n + 1 element'''

    
    return np.cumsum(1 / np.arange(1,n+1))

        




Test cases for problem 9

In [139]:
# WRITE YOUR TEST CASES HERE


harmonic_numbers(1000)

array([1.        , 1.5       , 1.83333333, 2.08333333, 2.28333333,
       2.45      , 2.59285714, 2.71785714, 2.82896825, 2.92896825,
       3.01987734, 3.10321068, 3.18013376, 3.25156233, 3.31822899,
       3.38072899, 3.43955252, 3.49510808, 3.54773966, 3.59773966,
       3.6453587 , 3.69081325, 3.73429151, 3.77595818, 3.81595818,
       3.85441972, 3.89145675, 3.92717104, 3.9616538 , 3.99498713,
       4.0272452 , 4.0584952 , 4.08879823, 4.11820999, 4.14678142,
       4.1745592 , 4.20158622, 4.22790201, 4.25354304, 4.27854304,
       4.30293328, 4.32674281, 4.34999862, 4.37272589, 4.39494812,
       4.41668725, 4.43796384, 4.45879718, 4.47920534, 4.49920534,
       4.51881318, 4.53804395, 4.55691188, 4.57543039, 4.59361221,
       4.61146935, 4.62901321, 4.64625459, 4.66320375, 4.67987041,
       4.69626386, 4.71239289, 4.7282659 , 4.7438909 , 4.75927552,
       4.77442703, 4.78935241, 4.80405829, 4.81855104, 4.83283676,
       4.84692126, 4.86081015, 4.87450878, 4.8880223 , 4.90135

**Problem 10**

**Concept:** *Numpy arrays, accumulator pattern.*

Compute Fibonacci numbers

**Task:**

Write a function `fibonacci(n)` that returns a numpy array containing the first `n` Fibonacci numbers.

The Fibonacci sequence is defined as:

​$$
F_0 = 0, \quad F_1 = 1
$$

$$
F_n = F_{n-1} + F_{n-2}
$$


Your function should:

1. Create a numpy array of length `n`

2. Initialize the first two values

3. Use a loop to compute each subsequent value using the previous two numbers

The function should return the final array of Fibonacci numbers as integers.


**Sample Output:**

If we call the function `finobacci(n)` where `n = 10`, it should return:

```
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34]
```


In [ ]:
# TO DO: WRITE YOUR SOLUTION HERE


def fibonacci(n):

    '''Here we are calculating the fib sequence of a group of numbers. we define the first element as 0 and the second as 1, and then compute from 2s'''


    result = np.empty(n, dtype=int) # initializing an empty numpy array 
    
    if n > 0:
        result[0] = 0
    if n > 1:
        result[1] = 1
        
    for i in range(2, n):
        result[i] = result[i - 1] + result[i - 2]
    
    return result
    



Test cases for problem 10

In [142]:
# WRITE YOUR TEST CASES HERE

n = 9

fibonacci(n)

array([ 0,  1,  1,  2,  3,  5,  8, 13, 21])

**Problem 11**

**Concept:** *Numpy arrays, linear algebra.*

**Task:**

Write a function linear_regression(x, y) that computes the linear regression coefficients of y as a function of x using linear algebra.

The regression coefficients should be computed using the normal equation:

$$
\beta = (X^T X)^{-1} X^T y
$$

Where:

- $X$ is the matrix of input variables
- $y$ is the vector of observed outputs
- $\beta$ is the vector of regression coefficients
- $X^T$ is the transpose of $X$


Your function should:

1. Convert the inputs into numpy arrays or matrices if necessary

2. Compute the regression coefficients using numpy matrix multiplication

3. Return the coefficient vector

The returned coefficients represent the intercept and slope(s) of the regression model.


Use numpy operations such as matrix multiplication (`@`) and transpose (`.T`) to compute the result.


**Sample Output:**

1-variable regression with intercept column

Consider the following:
```
x = np.array([[1, 1],
              [1, 2],
              [1, 3],
              [1, 4],
              [1, 5]])
y = np.array([[9],
              [12],
              [15],
              [18],
              [21]])
```

If we call the function `linear_regression(x, y)`, then it should return:
```
[[6. ],
 [3. ]]
```

Meaning: intercept = 6, slope = 3

In [ ]:
# TO DO: WRITE YOUR SOLUTION HERE



def linear_regression(x, y):

    '''We calculate the regression coeff from the linalg formula above'''

    x = np.array(x)
    y = np.array(y)
    return np.linalg.inv(x.T @ x) @ x.T @ y # view the formula above lol 
    
    


Test cases for problem 11

In [147]:
# WRITE YOUR TEST CASES HERE


x = np.array([[1, 1],
              [1, 2],
              [1, 3],
              [1, 4],
              [1, 5]])
y = np.array([[9],
              [12],
              [15],
              [18],
              [21]])




linear_regression(x, y)

array([[6.],
       [3.]])